export const Day1List = [
  {
    id: "d1E1",
    hrs_start_time: "10:00",
    start_time: "10 AM",
    end_time: "11:30 AM",
    hrs_end_time: "11:30",
    event_name: "Breakfast",
    event_description:
      "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit ",
    border: "1px transparent",
    backgroundColor: "transparent",
  },
  {
    id: "d1E2",
    hrs_start_time: "13:00",
    start_time: "1 PM",
    end_time: "3:30 PM",
    hrs_end_time: "15:30",
    event_name: "Lunch",
    event_description: "All's well that end's well",
    border: "1px transparent",
    backgroundColor: "transparent",
  },
  {
    id: "d1E3",
    hrs_start_time: "16:00",
    start_time: "4 PM",
    end_time: "5:30 PM",
    hrs_end_time: "17:30",
    event_name: "HighTea",
    event_description: "All's well that end's well",
    border: "1px transparent",
    backgroundColor: "transparent",
  },
  {
    id: "d1E4",
    hrs_start_time: "19:00",
    start_time: "7 PM",
    end_time: "9 PM",
    hrs_end_time: "21:00",
    event_name: "dinner",
    event_description: "All's well that end's well",
    border: "1px transparent",
    backgroundColor: "transparent",
  },
  {
    id: "d1E5",
    hrs_start_time: "19:00",
    start_time: "7 PM",
    end_time: "9 PM",
    hrs_end_time: "21:00",
    event_name: "dinner",
    event_description: "All's well that end's well",
    border: "1px transparent",
    backgroundColor: "transparent",
  },
  {
    id: "d1E6",
    hrs_start_time: "19:00",
    start_time: "7 PM",
    end_time: "9 PM",
    hrs_end_time: "21:00",
    event_name: "dinner",
    event_description: "All's well that end's well",
    border: "1px transparent",
    backgroundColor: "transparent",
  },
  {
    id: "d1E7",
    hrs_start_time: "19:00",
    start_time: "7 PM",
    end_time: "9 PM",
    hrs_end_time: "21:00",
    event_name: "dinner",
    event_description: "All's well that end's well",
    border: "1px transparent",
    backgroundColor: "transparent",
  },
  {
    id: "d1E8",
    hrs_start_time: "19:00",
    start_time: "7 PM",
    end_time: "9 PM",
    hrs_end_time: "21:00",
    event_name: "dinner",
    event_description: "All's well that end's well",
    border: "1px transparent",
    backgroundColor: "transparent",
  },
];
export const Day2List = [
  {
    id: "d2E1",
    hrs_start_time: "10:00",
    start_time: "10 AM",
    end_time: "11:30 AM",
    hrs_end_time: "11:30",
    event_name: "Breakfast",
    event_description:
      "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit ",
    border: "1px transparent",
    backgroundColor: "transparent",
  },
  {
    id: "d2E2",
    hrs_start_time: "13:00",
    start_time: "1 PM",
    end_time: "3:30 PM",
    hrs_end_time: "15:30",
    event_name: "Lunch",
    event_description: "All's well that end's well",
    border: "1px transparent",
    backgroundColor: "transparent",
  },
  {
    id: "d2E3",
    hrs_start_time: "16:00",
    start_time: "4 PM",
    end_time: "5:30 PM",
    hrs_end_time: "17:30",
    event_name: "HighTea",
    event_description: "All's well that end's well",
    border: "1px transparent",
    backgroundColor: "transparent",
  },
  {
    id: "d2E4",
    hrs_start_time: "19:00",
    start_time: "7 PM",
    end_time: "9 PM",
    hrs_end_time: "21:00",
    event_name: "dinner",
    event_description: "All's well that end's well",
    border: "1px transparent",
    backgroundColor: "transparent",
  },
];
